<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-ID7FLTM" name="com.PanaMCAutomation.MC_Carrier_Management.ID1290_TC047_Carrier_Dashboard_Carrier_Actions_Shipped_move_out_items" tests="1" failures="0" timestamp="11 Jan 2021 13:30:03 GMT" time="30.464" errors="1">
  <testcase name="testB" time="30.464" classname="com.PanaMCAutomation.MC_Carrier_Management.ID1290_TC047_Carrier_Dashboard_Carrier_Actions_Shipped_move_out_items">
    <error type="java.lang.reflect.InvocationTargetException">
      <![CDATA[java.lang.reflect.InvocationTargetException
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at com.PanaAutomation.Driver.DriverScript.executeKeywords(DriverScript.java:79)
at com.PanaMCAutomation.MC_Carrier_Management.ID1290_TC047_Carrier_Dashboard_Carrier_Actions_Shipped_move_out_items.testB(ID1290_TC047_Carrier_Dashboard_Carrier_Actions_Shipped_move_out_items.java:24)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
Caused by: java.lang.AssertionError: The following asserts failed:
Element not found 
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at com.PanaAutomation.Keywords.GenericKeywords.reportFailure(GenericKeywords.java:1469)
at com.PanaAutomation.Keywords.GenericKeywords.validatePopUpMessage(GenericKeywords.java:651)
... 31 more
]]>
    </error>
  </testcase> <!-- testB -->
</testsuite> <!-- com.PanaMCAutomation.MC_Carrier_Management.ID1290_TC047_Carrier_Dashboard_Carrier_Actions_Shipped_move_out_items -->
